version: "3.8"
services:
  postgres:
    container_name: zkorum_postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CHANGEME
      POSTGRES_DB: zkorum
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./services/back/database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    expose:
      - "5432"
    restart: unless-stopped
  pgadmin:
    container_name: zkorum_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@zkorum.com
      PGADMIN_DEFAULT_PASSWORD: CHANGEME
    volumes:
      - pgadmin:/var/lib/pgadmin
    expose:
      - "80"
    restart: unless-stopped
  back:
    container_name: zkorum_back
    image: zkorum/back:0.4.0
    environment:
      CONNECTION_STRING: "postgres://postgres:CHANGEME@postgres:5432/zkorum"
      AWS_ACCESS_KEY_ID: "CHANGEME"
      AWS_SECRET_ACCESS_KEY: "CHANGEME"
      PK_VERSION: 2
      PRIVATE_KEY_FILEPATH: /run/secrets/iss_sk_v2
      NODE_ENV: "production"
    secrets:
      - iss_sk_v2
    expose:
      - "8080"
    restart: unless-stopped
  front:
    container_name: zkorum_front
    image: zkorum/front:0.4.5
    expose:
      - "80"
    restart: unless-stopped
  landing-page:
    container_name: zkorum_landing-page
    image: zkorum/landing-page:1.0.0
    expose:
      - "80"
    restart: unless-stopped
  nginx:
    image: nginx:stable-alpine
    container_name: zkorum_nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 5050:5050
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email admin@zkorum.com --agree-tos --no-eff-email -d zkorum.com
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/logs:/var/log/letsencrypt

volumes:
  postgres:
  pgadmin:

secrets:
  iss_sk_v2:
    external: true
